---
- name: update web and nfs
  hosts: webservers, nfs 
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update lb and db servers
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Print gathered facts
      debug:
        var: ansible_facts

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest